name: Build 
run-name: ${{ github.actor }} is building 🚀
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - run: npm ci
      - run: npm run build
      - run: npm test

      - run: echo "This job's status is ${{ job.status }}."

